name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: FAZER O CHECKOUT DO CÓDIGO
      uses: actions/checkout@v4

    - name: DEFINIR A VERSÃO DO NODE.JS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: INSTALAR DEPENDÊNCIAS
      run: npm install

    - name: INICIAR A API REST 
      run: npm start &

    - name: AGUARDAR INICIALIZAÇÃO DA API
      run: sleep 5

    - name: EXECUTAR OS TESTES 
      run: npm run test


